name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.PI_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
            cd ~/myapp
            git pull
#            echo "${{ secrets.SOPS_KEY }}" > sops.key
#            export SOPS_AGE_KEY_FILE=./sops.key
#            sops -d secrets/secrets.enc.yaml > secrets/app.env
            docker-compose up -d --build
          EOF